#!/usr/bin/python2.7

import rospy
import numpy as np
import cv2
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image
from sensor_msgs.msg import CompressedImage

def imagecallback(msg):
    global depth_filter

    img = bridge.compressed_imgmsg_to_cv2(msg,'bgr8')
    img = img*depth_filter
    img_pub.publish(bridge.cv2_to_imgmsg(img))

def depthcallback(msg):
    global depth_filter
    depth = bridge.imgmsg_to_cv2(msg, msg.encoding)
    width = msg.width
    height = msg.height
    
    depth_filter[height/2-10:height/2+10, width/2-10:width/2+10] = 0
    print(depth_filter[height/2,width/2])

if __name__ == '__main__':
    rospy.init_node('depthfilter_test')

    bridge = CvBridge()
    depth_filter = np.ones(height,width)
    depth_msg = '/camera/depth/image_rect_raw'
    depth_sub = rospy.Subscriber(depth_msg, Image, depthcallback)
    
    img_topic = '/camera/color/image_raw/compressed'
    img_sub = rospy.Subscriber(img_topic, CompressedImage, imagecallback)
    img_pub = rospy.Publisher('image_topic',Image,queue_size='10')
    
    rate = rospy.Rate(30)
    rospy.spin()
    rate.sleep()
